### ISSUE TITLE
about deeplab setting

### ISSUE THREAD

**Issue by mt-cly** [CVI-SZU/CLIMS#10]
Hi, thanks for your great work.
I notice that in the last step of training segmentation, the  deeplabv1 with WResNet38 outperforms others. However, I does not find the WResNet38 backbone in  the provided link  of https://github.com/kazuto1011/deeplab-pytorch . I wonder if you reproduce it? Can you please provide the code about DeepLabv1(WResNet38) or tell me where I can find relevant code? 
Thanks.

**Comment by Sierkinhane** [comment]
Hi! The code is available at [here](https://github.com/YudeWang/semantic-segmentation-codebase/tree/main/experiment/seamv1-pseudovoc). Note that I also apply multi-scale training from [here](https://github.com/kazuto1011/deeplab-pytorch) to the above implementation. Actually, I recommend to adopt deeplabv2 for fair comparison to previous methods.

**Comment by mt-cly** [comment]
Yes, I get it. Thanks.
