### ISSUE TITLE
是否可提供训练好的权重档作复现?

### ISSUE THREAD

**Issue by hung334** [CVI-SZU/CLIMS#14]
您好，想请教是否可提供训练好的权重档?

因为我照您的训练步骤做复现，训练多次后得出初始CAMS的mIoU均值只有54.449，标准差0.0811，未能达到论文提及的56.6指标。

**Comment by Sierkinhane** [comment]
You can download the weights of CLIMS at [here](https://drive.google.com/file/d/1jcL92bUgA76cMI5FW5bcOKdbvlVLhbCF/view?usp=share_link).
