### ISSUE TITLE
Please check the Pascal VOC train_aug. 

### ISSUE THREAD

**Issue by Bala93** [CVI-SZU/CLIMS#19]
I have changed this line "https://github.com/CVI-SZU/CLIMS/blob/master/segmentation/deeplabv2/libs/datasets/voc.py#L150' to the following to start the training 

file_list = [id_.rstrip().split(" ")[0].split('/')[-1].split('.')[0] for id_ in file_list]

**Comment by Sierkinhane** [comment]
Hi, maybe [this issue](https://github.com/CVI-SZU/CLIMS/issues/15) can work for the problem.

**Comment by Bala93** [comment]
Ok, I think with this format, it should work. I downloaded from other source, where it had both img and mask.
