### ISSUE TITLE
关于梯度

### ISSUE THREAD

**Issue by xiaoyuan1996** [CVI-SZU/CLIMS#5]
您好，使用clip进行图文相似度计算，继而用来监督mask生成的idea之前也有考虑过。可当时实现时候因为clip的层数极深，造成算出的loss在优化前端模型时，无法得到有力的梯度。咨询下您是否有遇到过这个问题。

**Comment by Sierkinhane** [comment]
您好，我们是有遇到这种问题的，我们组里做的GAN和这篇文章都遇到了，具体表现是优化比较慢，迭代时间长。这个工作的话我是对每个loss term使用一个比较大的系数，同时，backbone如果有一个较好的初始化也可以比较好地加快激活图的优化。
