### ISSUE TITLE
Hi,should I create a directory cam-baseline-voc12?

### ISSUE THREAD

**Issue by yangxinhaosmu** [CVI-SZU/CLIMS#6]
Should I create a directory cam-baseline-voc12 and put res50_cam.pth in it? 
Is the res50_cam.pth pre-trained on ImageNet by your team? 
What is the difference between this res50_cam.pth and net/resnet50_cam.py trained by myself?
If I run the run_sample.py command line, am I just train your .pth more time(epoch) or I train the model from scratch?
Sorry to ask such many easy questions, I am the beginner of WSSS. Thank you so much!

**Comment by Sierkinhane** [comment]
Hi, 
1. I provided res50_cam.pth which was the pre-trained model on VOC2012. Actually, you can try to train such a model or directly use ours.
2. Then, run_sample.py will load the pretrained model to train clims.

**Comment by yangxinhaosmu** [comment]
> Hi,
> 
> 1. I provided res50_cam.pth which was the pre-trained model on VOC2012. Actually, you can try to train such a model or directly use ours (create a directory called cam-baseline-voc12 then put the pretrained res50_cam.pth in it).
> 2. resnet50_cam.py is the basic network (baseline cam). res50_cam.pth is the saved model of resnet50_cam.py
> 3. run_sample.py will load the pretrained model to train clims.
>    btw, welcome to star our repository

**Comment by yangxinhaosmu** [comment]
> Hi,
> 
> 1. I provided res50_cam.pth which was the pre-trained model on VOC2012. Actually, you can try to train such a model or directly use ours (create a directory called cam-baseline-voc12 then put the pretrained res50_cam.pth in it).
> 2. resnet50_cam.py is the basic network (baseline cam). res50_cam.pth is the saved model of resnet50_cam.py
> 3. run_sample.py will load the pretrained model to train clims.
>    btw, welcome to star our repository

1.感谢，我目前的理解是先用res50_cam.pth的模型去初始化resnet50_clims里的CLIMS对吗？
2.还有一个问题就是如果我想CLIP的image encoder之前加一些模块（比如对特征表示做增强这种的）的话，可以在resnet50_clims里的CLIMS的stage后面直接加吗？这样的话还能用res50_cam.pth去初始化吗？

**Comment by Sierkinhane** [comment]
可以的，如果你添加了一些模块的话，也可以导入预训练的模型，只要把这里的strict=True换成strict=False https://github.com/CVI-SZU/CLIMS/blob/f37162c1fba3a0011600a6eadfe97fc16edd7edd/step/train_clims.py#L65

**Comment by yangxinhaosmu** [comment]
> 可以的，如果你添加了一些模块的话，也可以导入预训练的模型，只要把这里的strict=True换成strict=False
> 
> https://github.com/CVI-SZU/CLIMS/blob/f37162c1fba3a0011600a6eadfe97fc16edd7edd/step/train_clims.py#L65

我大概了解了，还有一个小小的问题，就是如果不导入res50_cam.pth的话，训练resnet50_clims大概需要多花多少时间呢？您有记录过吗？

**Comment by Sierkinhane** [comment]
最好导入一下预训练模型，效果会好些，总体训练时间是一样的应该是10epoch

**Comment by yangxinhaosmu** [comment]
> 最好导入一下预训练模型，效果会好些，总体训练时间是一样的应该是10epoch

OK! 感谢同学耐心的指导！！！祝申到理想的PHD!

**Comment by Sierkinhane** [comment]
感谢！
