### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by linyq2117** [CVI-SZU/CLIMS#7]
Thanks for your great work!

Could you share the approximate training time for each stage (CLIP-finetune, CLIMS, and affinitynet)? This will help me a lot.

**Comment by Sierkinhane** [comment]
Hi, maybe within 2-3 hours each on pascal voc2012 but additional time of post-processing is needed to generate affinity labels or irnet labels. Note that It is unnecessary to finetune CLIP in the latest code for clims. BTW, welcome to star our project.

**Comment by linyq2117** [comment]
Thanks a lot!
