### ISSUE TITLE
About The quality of initial CAMs

### ISSUE THREAD

**Issue by Big-Brother-Pikachu** [CVI-SZU/CLIMS#8]
Hi, thanks for sharing this great work. I have some detail questions regarding the results in [https://github.com/CVI-SZU/CLIMS#the-quality-of-initial-cams-and-pseudo-masks-on-pascal-voc2012](url). First, I think these results (56.6 / 58.6) is evaluated on the train set. But which one, the 1464 images original one or the 10582 images augmented one? Second, are these results (56.6 / 58.6) obtained after dCRF or not? If not, has dCRF participated in your pipeline? As far as I understand, following codes: 
https://github.com/CVI-SZU/CLIMS/blob/1b9518b88485f4fdf7be2c7451bcad9ad33c0847/step/cam_to_ir_label.py#L37
makes dCRF not contribute to the (56.6 / 58.6) results, but to the (70.5 / 73) results. Am I right?
Looking forward to your reply. Thanks!

**Comment by Sierkinhane** [comment]
Hi, dCRF was not included in the latest code to refine the generated actication maps. Note that `cam_to_ir_label.py` is the code to generate labels for training IRNet. Then we use IRNet to refine the generated activation maps as the pseudo semantic masks. Results of 58.6 and 73 mIOU are for `train_set`.

**Comment by Sierkinhane** [comment]
BTW, welcome to star our project!

**Comment by Sierkinhane** [comment]
Exactly. Well, maybe you should compare the results in our cvpr version, i.e., 56.6.

**Comment by Big-Brother-Pikachu** [comment]
Get it! Thanks for your patience and clear explanation. I will close this issue now.
